### ISSUE TITLE
H2 is always reverting with error , but when I simulate whole process on local it works

### ISSUE THREAD

**Issue by AsthaMishra** [PatrickAlphaC/smartcon-hacker-house-hunt-rules#1]
logs from Remix:

[
	{
		"from": "0xd8b934580fcE35a11B58C6D73aDeE468a2833fa8",
		"topic": "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef",
		"event": "Transfer",
		"args": {
			"0": "0x0000000000000000000000000000000000000000",
			"1": "0xf8e81D47203A594245E36C48e151709F0C19fBe8",
			"2": "0",
			"from": "0x0000000000000000000000000000000000000000",
			"to": "0xf8e81D47203A594245E36C48e151709F0C19fBe8",
			"tokenId": "0"
		}
	}
]

**Comment by PatrickAlphaC** [comment]
Hi, sorry, I'm not monitoring this repo anymore. Thanks!
